apiVersion: serving.kserve.io/v1alpha1
kind: InferenceGraph
metadata:
  name: dog-poem-pipeline
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  nodes:
    root:
      routerType: Sequence
      steps:
        # Identify the dog breed
        - name: dog-breeds-classifier
          serviceName: dog-breeds-classifier
        # Write a poem about the dog breed
        - name: vllm-llama3-8b
          serviceName: vllm-llama3-8b
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

